import java.nio.file.Files
import java.nio.file.StandardCopyOption

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-application-conventions")
    id("org.openjfx.javafxplugin") version "0.1.0"
}

val hotswapAgent = configurations.create("hotswapAgent") {
    isCanBeConsumed = false
    isCanBeResolved = true
    isTransitive = false
}

// Development-only sources that are compiled and added to the classpath exclusively by hotRun.
// They are not part of the main JAR or application distribution.
val hotReload = sourceSets.create("hotreload") {
    compileClasspath += sourceSets.main.get().output
    runtimeClasspath += output + compileClasspath
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation("io.github.cdimascio:dotenv-java:3.0.0")

    // Only development sources compile against the agent API. HotswapAgent supplies its
    // implementation to hotRun; production compilation and packaging do not see this dependency.
    add(hotReload.compileOnlyConfigurationName, "org.hotswapagent:hotswap-agent-core:2.0.3")

    add(hotswapAgent.name, "org.hotswapagent:hotswap-agent:2.0.3")
}

application {
    // Define the main class for the application.
    mainClass = "com.acteque.terminal.App"
}

tasks.named<JavaExec>("run") {
    jvmArgs("--enable-native-access=javafx.graphics")
}

// JetBrains Runtime currently provides enhanced class redefinition on Java 25, while the regular
// project toolchain remains on Java 26. Keep a separate Java 25-compatible output for hot reload so
// normal builds and packaging are unaffected.
val hotCompilerWorkspace = "emulator-hot-${rootProject.projectDir.absolutePath.hashCode()}"
val compiledHotClassesDirectory = layout.dir(providers.provider {
    file("${System.getProperty("java.io.tmpdir")}/$hotCompilerWorkspace/classes")
})
val hotClassesDirectory = layout.buildDirectory.dir("classes/java/hot")
val hotResourcesDirectory = layout.buildDirectory.dir("resources/hot")

val compileHotJava = tasks.register<JavaCompile>("compileHotJava") {
    group = "application"
    description = "Compiles Java 25-compatible classes for HotswapAgent."

    source(sourceSets.main.get().java)
    source(hotReload.java)
    classpath = sourceSets.main.get().compileClasspath + hotReload.compileClasspath
    destinationDirectory.set(compiledHotClassesDirectory)
    javaCompiler.set(javaToolchains.compilerFor {
        languageVersion.set(JavaLanguageVersion.of(25))
        vendor.set(JvmVendorSpec.JETBRAINS)
    })
    options.release.set(25)
    options.encoding = "UTF-8"

    // Gradle continuous mode can occasionally detect a rapid save but reuse its previous
    // up-to-date snapshot, leaving HotswapAgent with no new class file to load. Continuous mode
    // only invokes this task after an input change, so recompiling here is intentional.
    outputs.upToDateWhen { false }
}

val publishHotClasses = tasks.register("publishHotClasses") {
    group = "application"
    description = "Copies compiled classes into the stable directory watched by HotswapAgent."
    dependsOn(compileHotJava)
    doNotTrackState("The staging directory must not become a continuous-build watch input.")

    doLast {
        val sourceRoot = compiledHotClassesDirectory.get().asFile.toPath()
        val targetRoot = hotClassesDirectory.get().asFile.toPath()

        val paths = Files.walk(sourceRoot)
        try {
            paths.filter { Files.isRegularFile(it) }.forEach { source ->
                val target = targetRoot.resolve(sourceRoot.relativize(source))
                Files.createDirectories(target.parent)

                if (!Files.exists(target) || Files.mismatch(source, target) != -1L) {
                    Files.copy(
                        source,
                        target,
                        StandardCopyOption.REPLACE_EXISTING,
                    )
                }
            }
        } finally {
            paths.close()
        }
    }
}

val processHotResources = tasks.register<Copy>("processHotResources") {
    group = "application"
    description = "Copies application resources for the hot-reload runtime."

    from(sourceSets.main.get().resources)
    from(hotReload.resources)
    into(hotResourcesDirectory)
}

val hotClasses = tasks.register("hotClasses") {
    group = "application"
    description = "Builds the classes and resources watched by HotswapAgent."
    dependsOn(publishHotClasses, processHotResources)
}

tasks.register<JavaExec>("hotRun") {
    group = "application"
    description = "Runs the JavaFX application with enhanced class redefinition."
    dependsOn(hotClasses)

    mainClass.set(application.mainClass)
    javaLauncher.set(javaToolchains.launcherFor {
        languageVersion.set(JavaLanguageVersion.of(25))
        vendor.set(JvmVendorSpec.JETBRAINS)
    })
    jvmArgs(
        "-XX:+AllowEnhancedClassRedefinition",
        "-XX:HotswapAgent=external",
        "-Xlog:redefine+class*=info",
    )

    doFirst {
        val runtimeFiles = configurations.runtimeClasspath.get().files
        val javaFxFiles = runtimeFiles.filter { it.name.startsWith("javafx-") }
        val applicationFiles = runtimeFiles - javaFxFiles.toSet()

        classpath = files(hotClassesDirectory, hotResourcesDirectory, applicationFiles)
        jvmArgs(
            "--module-path", javaFxFiles.joinToString(File.pathSeparator),
            "--add-modules", "javafx.graphics",
            "--enable-native-access=javafx.graphics",
            "-javaagent:${hotswapAgent.singleFile.absolutePath}=autoHotswap=true",
        )
    }
}

javafx {
    version = "25.0.1"
    modules = listOf("javafx.graphics")
}
