/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-application-conventions")
    id("org.openjfx.javafxplugin") version "0.1.0"
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation("io.github.cdimascio:dotenv-java:3.0.0") 
}

application {
    // Define the main class for the application.
    mainClass = "com.emulator.app.App"
}

tasks.named<JavaExec>("run") {
    jvmArgs("--enable-native-access=javafx.graphics")
}

javafx {
    version = "25.0.1"
    modules = listOf("javafx.graphics")
}
