/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-application-conventions")
    id("org.openjfx.javafxplugin") version "0.1.0"
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":market-data:core"))
    implementation(project(":market-data:tiingo"))
    implementation(project(":market-logos:core"))
    implementation(project(":market-logos:elbstream"))
    implementation(project(":ui:core"))
    implementation(project(":ui:icons"))
    implementation("io.github.cdimascio:dotenv-java:3.0.0")
}

application {
    // Define the main class for the application.
    mainClass = "com.acteque.terminal.App"
}

tasks.named<JavaExec>("run") {
    workingDir(rootProject.projectDir)
    jvmArgs("--enable-native-access=javafx.graphics")
}

tasks.withType<Test>().configureEach {
    jvmArgs("--enable-native-access=ALL-UNNAMED")
    // JavaFX focus tests share the desktop and need separate test processes in sequence.
    mustRunAfter(":ui:core:test", ":ui:icons:test")
}

javafx {
    version = "25.0.1"
    modules = listOf("javafx.controls")
}
