// Generated by tools/generate-lucide-icons.mjs from @lucide/icons 1.40.0. Do not edit.
package com.acteque.terminal.ui.icons;

/** Lucide icon geometry included in the application. */
public enum LucideIcons implements LucideGlyph {
  CHECK("check", 24, 24, "M0 0M20 6 9 17l-5-5"),

  CHEVRON_DOWN("chevron-down", 24, 24, "M0 0m6 9 6 6 6-6"),

  CHEVRON_UP("chevron-up", 24, 24, "M0 0m18 15-6-6-6 6"),

  PLUS("plus", 24, 24, "M0 0M5 12h14 M0 0M12 5v14"),

  SEARCH(
    "search",
    24,
    24,
    "M0 0m21 21-4.34-4.34 M3 11A8 8 0 1 0 19 11A8 8 0 1 0 3 11"
  ),

  SETTINGS(
    "settings",
    24,
    24,
    "M0 0M9.671 4.136a2.34 2.34 0 0 1 4.659 0 2.34 2.34 0 0 0 3.319 1.915 2.34 2.34 0 0 1 2.33 4.033 2.34 2.34 0 0 0 0 3.831 2.34 2.34 0 0 1-2.33 4.033 2.34 2.34 0 0 0-3.319 1.915 2.34 2.34 0 0 1-4.659 0 2.34 2.34 0 0 0-3.32-1.915 2.34 2.34 0 0 1-2.33-4.033 2.34 2.34 0 0 0 0-3.831A2.34 2.34 0 0 1 6.35 6.051a2.34 2.34 0 0 0 3.319-1.915 M9 12A3 3 0 1 0 15 12A3 3 0 1 0 9 12"
  ),

  X("x", 24, 24, "M0 0M18 6 6 18 M0 0m6 6 12 12");

  private final String sourceName;
  private final double width;
  private final double height;
  private final String pathData;

  LucideIcons(String sourceName, double width, double height, String pathData) {
    this.sourceName = sourceName;
    this.width = width;
    this.height = height;
    this.pathData = pathData;
  }

  @Override
  public String sourceName() {
    return sourceName;
  }

  @Override
  public double width() {
    return width;
  }

  @Override
  public double height() {
    return height;
  }

  @Override
  public String pathData() {
    return pathData;
  }
}
